title: Rigo Ramírez - Blog
description: > # this means to ignore newlines until "baseurl:"
  Aprender - Aplicar - Compartir - Repetir.
  Compartiendo lo aprendido en la vida con enfásis en temas de programación y otros no-tech.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:categories/:title/

author:
  name: 'Rigo Ramírez'
  email: ram_ri@outlook.com
  twitter_username: reegoram
  github_username:  reegoram
  linkedin_username: reegoram

paginate: 2

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock